# Generated by Django 4.2.2 on 2024-04-30 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("authtoken", "0004_alter_tokenproxy_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vendor_management", "0003_customtoken"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customtoken",
            options={},
        ),
        migrations.RemoveField(
            model_name="customtoken",
            name="created",
        ),
        migrations.RemoveField(
            model_name="customtoken",
            name="key",
        ),
        migrations.AddField(
            model_name="customtoken",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="2",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customtoken",
            name="token",
            field=models.OneToOneField(
                default="123",
                on_delete=django.db.models.deletion.CASCADE,
                to="authtoken.token",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customtoken",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
